const DEFAULT_TEST_ENV = {
	NODE_ENV: 'development',
	FILE_LOG_LEVEL: 'error',
	LOG_FILE_PATH: 'logs/test.log',
	CONSOLE_LOG_LEVEL: 'silent',
	ENABLE_CONSOLE_PRETTY_LOGS: 'false',
	DATABASE_URL: 'postgresql://arbiter:arbiter@localhost:5432/arbiter_test',
	REDIS_HOST: 'localhost',
	REDIS_PORT: '6379',
	REDIS_PASSWORD: 'arbiter',
	REDIS_DB: '0',
	DISCORD_TOKEN: 'test-discord-token',
	DISCORD_GUILD_ID: 'test-guild-id',
	WELCOME_CHANNEL_ID: 'welcome-channel-id',
	WELCOME_RULES_CHANNEL_ID: 'welcome-rules-channel-id',
	WELCOME_RECRUITMENT_CHANNEL_ID: 'welcome-recruitment-channel-id',
	WELCOME_ROLE_SELECT_CHANNEL_ID: 'welcome-role-select-channel-id',
	WELCOME_CHARTER_CHANNEL_ID: 'welcome-charter-channel-id',
	WELCOME_NEW_PLAYERS_CHANNEL_ID: 'welcome-new-players-channel-id',
	BOT_REQUESTS_CHANNEL_ID: 'bot-requests-channel-id',
	EXEC_ROLE_ID: 'exec-role-id',
	SEC_ROLE_ID: 'sec-role-id',
	TECH_ROLE_ID: 'tech-role-id',
	CMD_ROLE_ID: 'cmd-role-id',
	TIR_ROLE_ID: 'tir-role-id',
	ANG_ROLE_ID: 'ang-role-id',
	CENT_ROLE_ID: 'cent-role-id',
	NVY_L_ROLE_ID: 'nvy-l-role-id',
	MRN_L_ROLE_ID: 'mrn-l-role-id',
	SUP_L_ROLE_ID: 'sup-l-role-id',
	NVY_ROLE_ID: 'nvy-role-id',
	MRN_ROLE_ID: 'mrn-role-id',
	SUP_ROLE_ID: 'sup-role-id',
	LGN_ROLE_ID: 'lgn-role-id',
	INT_ROLE_ID: 'int-role-id',
	RES_ROLE_ID: 'res-role-id',
	EVENT_TRACKING_CHANNEL_ID: 'event-tracking-channel-id',
	EVENT_TRACKING_INTERVAL_SECONDS: '15',
	EVENT_MERIT_DEFAULT_MIN_ATTENDANCE_PCT: '50'
} as const;

for (const [key, value] of Object.entries(DEFAULT_TEST_ENV)) {
	process.env[key] = value;
}
